#!/bin/sh

BASE=$(cd "$(dirname "$0")"; pwd -P)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload ~/.vim/.swap ~/.vim/.undo
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mkdir -pv .bak
mv -v ~/.vimrc .bak/.vimrc.old 2> /dev/null
mv -v ~/.config/nvim/coc-settings.json .bak/.coc-settings.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc
ln -sfv $BASE/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sv $BASE/indent ~/.vim/indent
vim +PlugInstall +qall

