#!/bin/sh
BASE=$(cd "$(dirname "$0")"; pwd -P)
FISH_CONF=$BASE/fish
FISH_INSTALL_DIR=$HOME/.config/fish

mkdir -pv .bak
mkdir -pv $FISH_INSTALL_DIR

for f in $(ls $FISH_CONF); do
	mv -vfT $FISH_INSTALL_DIR/$f .bak/$f 2> /dev/null
	ln -sfv $FISH_CONF/$f $FISH_INSTALL_DIR/$f
done

