#!/bin/sh

BASE=$(cd "$(dirname "$0")"; pwd -P)

mkdir -pv .bak
for rc in $(ls $BASE/configs); do
  [ -e ~/."$rc" ] && rm -rf .bak/."$rc" && mv -v ~/."$rc" .bak/."$rc"
  ln -sfv "$BASE/configs/$rc" ~/."$rc"
done

mkdir -pv $HOME/.config/nvim
mkdir -pv $HOME/.config/alacritty

ln -sfv $BASE/coc-settings.json $HOME/.config/nvim/coc-settings.json
ln -sfv $BASE/alacritty.yml $HOME/.config/alacritty/alacritty.yml
ln -sfv $BASE/configs/$rc ~/.$rc
