# ~/.tmux.conf

###########################################################################
set -g mouse off
# Toggle mouse on
bind m \
    set -g mouse on \;\
    display 'Mouse: ON'

# Toggle mouse off
bind M \
    set -g mouse off \;\
    display 'Mouse: OFF'

# Default termtype. If the rcfile sets $TERM, that overrides this value.
set -g default-terminal screen-256color

source "/Users/sinon/Library/Python/2.7/lib/python/site-packages/powerline/bindings/tmux/powerline.conf"

