source "/Users/sinon/Library/Python/2.7/lib/python/site-packages/powerline/bindings/tmux/powerline.conf"
set -s escape-time 0
set -g mouse off
set -g default-terminal screen-256color

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 10  # 向左扩展
bind L resize-pane -R 10  # 向右扩展
bind K resize-pane -U 5   # 向上扩展
bind J resize-pane -D 5   # 向下扩展

bind '"' split-window -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'

bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

