#!/bin/sh

BASE=$(pwd)
mkdir -pv .bak
for rc in $(ls); do
  [ -e ~/."$rc" ] && rm -rf .bak/."$rc" && mv -v ~/."$rc" .bak/."$rc"
  ln -sfv "$BASE/$rc" ~/."$rc"
done

mkdir -pv ~/.vim/.swap ~/.vim/.undo
