set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'mattdavis90/base16-tmux'
set -g @plugin 'xltan/tmux-open'
set -g @plugin 'xltan/tmux-fzf-url'
set -g @plugin 'junegunn/tmux-fzf-maccy'
set -g @plugin 'laktak/extrakto'

set -g @fzf-url-bind 'i'
set -g @colors-base16 'tomorrow-night'
set -g @open 'x'
set -g @open-editor 'C-x'
set -g @open-S 'https://www.google.com/search?q='
set -g @fzf-maccy-layout '-p50%'

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-copycat'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @plugin 'xltan/nord-tmux'
# set -g @nord_tmux_show_status_content "0"
# set -g @nord_tmux_no_patched_font "1"
# set -g @plugin 'christoomey/vim-tmux-navigator'

# for vim
# set -g @resurrect-strategy-vim 'session'
# # for neovim
# set -g @resurrect-strategy-nvim 'session'
# set -g @resurrect-capture-pane-contents 'on'
if-shell '[[ -z $SSH_TTY ]]' 'unbind-key C-b; set -g prefix C-g; bind C-g send-prefix'

set -g @copy_mode_put 'Enter'

set -g renumber-windows on

set -g word-separators " -()@.,[]{}:="
set -g mode-keys vi
set -g main-pane-width 65%
set -g main-pane-height 80%
set -g status-left-length 16
set -g mouse on

bind C-g set -g mouse 
unbind-key -T copy-mode-vi v
bind -T copy-mode-vi i switch-client -T text-object
bind -T text-object w if -F '#{selection_present}' { send -X select-word }
bind -T copy-mode-vi v if -F '#{selection_present}' { send -X clear-selection } { send -X begin-selection }
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi Y send -X begin-selection \; send-key $ \; send-key h \; send-key y

bind-key / copy-mode \; send-key ?
# bind-key -T copy-mode-vi C-g send-keys -X page-up
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Fix titlebar
set -g set-titles on
set -g set-titles-string "#T"

# Add truecolor support
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ',xterm*:smglr=\E7\E[?69h\E[%i%p1%d;%p2%ds\E8:mgc=\E7\E[?69l\E8'

bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
bind "'" command-prompt -1 -p "pane index:"  "select-pane -t '%%'"

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind m last-window

bind u select-pane -t.0 \; resize-pane -Z
bind _ select-layout main-horizontal \; swap-pane -t.0 \; select-pane -t.0
bind | select-layout main-vertical \; swap-pane -t.0 \; select-pane -t.0

bind C-l clear-history

run '~/.tmux/plugins/tpm/tpm'
