set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'
# set -g @plugin 'xltan/nord-tmux'
set -g @plugin 'mattdavis90/base16-tmux'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @nord_tmux_show_status_content "0"
# set -g @nord_tmux_no_patched_font "1"
set -g @colors-base16 'tomorrow-night'

# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

bind C-b set -g mouse
set -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Fix titlebar
set -g set-titles on
set -g set-titles-string "#T"

bind H resize-pane -L 10  # 向左扩展
bind L resize-pane -R 10  # 向右扩展
bind K resize-pane -U 5   # 向上扩展
bind J resize-pane -D 5   # 向下扩展

bind '"' split-window -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'
bind m split-window -h -c '#{pane_current_path}' \; resize-pane -x 70

# Add truecolor support
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ',xterm*:smglr=\E7\E[?69h\E[%i%p1%d;%p2%ds\E8:mgc=\E7\E[?69l\E8'

run '~/.tmux/plugins/tpm/tpm'

## default statusbar colors
#set-option -g status-bg colour238 #base02
#set-option -g status-fg colour136 #yellow
#set-option -g status-attr default

## default window title colors
#set-window-option -g window-status-fg colour244 #base0
#set-window-option -g window-status-bg default
##set-window-option -g window-status-attr dim

## active window title colors
#set-window-option -g window-status-current-fg colour166 #orange
#set-window-option -g window-status-current-bg default
##set-window-option -g window-status-current-attr bright

## pane border
#set-option -g pane-border-fg colour238 #base02
#set-option -g pane-active-border-fg colour240 #base01

## message text
#set-option -g message-bg colour238 #base02
#set-option -g message-fg colour166 #orange

## pane number display
#set-option -g display-panes-active-colour colour33 #blue
#set-option -g display-panes-colour colour166 #orange

## clock
#set-window-option -g clock-mode-colour colour64 #green

## bell
#set-window-option -g window-status-bell-style fg=colour238,bg=colour160 #base02, red
